---
# tasks file for cfg

- copy: src=roles/cfg/files/ dest=/home/ubuntu/devops/servers/ owner=nagios group=nagios mode=0755

- command: /home/ubuntu/devops/servers/generate.sh
  become: true

- command: /etc/init.d/nagios restart
  become: true
